### PR TITLE
Misc fixes/additions and restructured the flow to make more sense (to me anyways)

### PR DESCRIPTION
**Pull request by cjpetrus**
Fixed flow/logic to make maxTimeout behave correctly, but then got started on async checks + page termination corrected (still give time for new requests) + callback and event listener corrections and other misc things.

### CODE REVIEW

**Comment by kimmobrunfeldt** [comment]
I will try to check, merge and release this PR tomorrow. I'll warn that if I don't have time to do that, I won't be available for 3 weeks :/ I'm sorry if this will be the case - let's see tomorrow.

**Comment by kimmobrunfeldt** [comment]
As I feared, I didn't have time to do anything about this today. Sorry for the delay. Meanwhile you can depend directly from your fork in github by using a git+ url in package.json

**Comment by cjpetrus** [comment]
cool man, no worries! have a good 3 weeks!

**Comment by cjpetrus** [comment]
here :)

**Pull request closed without merging**
