### PR TITLE
Added support for cropping and setting image type and quality

### PR DESCRIPTION
**Pull request by Magiweb**

### CODE REVIEW

**Comment by kimmobrunfeldt** [comment]
This looks very good but still needs two things before I can merge and release.
- [x] Commandline arguments for urltoimage with the current convention
- [x] Documentation

**Comment by Magiweb** [comment]
@kimmobrunfeldt I think this'll do it! Please check my work on the CLI side - I'm not very au fait with using and configuring CLI or the use of yargs.

**Comment by kimmobrunfeldt** [comment]
Thanks! I'll merge this for now and add some minor fixes to cli arguments on master

**Comment by Magiweb** [comment]
Awesome - thanks!

**Pull request merged**
